"use strict";(()=>{var e={};e.id=388,e.ids=[388],e.modules={53524:e=>{e.exports=require("@prisma/client")},72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},48783:(e,r,t)=>{t.r(r),t.d(r,{originalPathname:()=>h,patchFetch:()=>x,requestAsyncStorage:()=>m,routeModule:()=>c,serverHooks:()=>w,staticGenerationAsyncStorage:()=>g});var a={};t.r(a),t.d(a,{POST:()=>l,dynamic:()=>u});var n=t(79182),s=t(72007),o=t(56719),i=t(93442),d=t(15649),p=t(11826);let u="force-dynamic";async function l(e){try{let r=await (0,d.getServerSession)(p.L);if(!r?.user)return i.NextResponse.json({error:"Unauthorized"},{status:401});let{message:t,conversation:a}=await e.json(),n=`You are an expert AI wedding planning assistant. You help couples plan their perfect wedding by providing personalized advice, recommendations, and guidance. You have extensive knowledge about:

- Wedding budgeting and cost management
- Wedding timelines and planning schedules  
- Global wedding venues and vendors
- Wedding traditions from various cultures and religions
- Wedding attire and fashion advice
- Catering and menu planning
- Photography and videography
- Flowers and decorations
- Music and entertainment
- Legal requirements for marriages worldwide
- Wedding etiquette and protocols

Always provide helpful, accurate, and practical advice. Be warm, encouraging, and supportive. If you don't know something specific, acknowledge it and suggest ways the couple can find the information they need.

Provide global wedding advice and adapt recommendations based on the couple's location when mentioned.`,s=[{role:"system",content:n},...a?.slice(-5)?.map(e=>({role:e?.type==="user"?"user":"assistant",content:e?.content}))||[],{role:"user",content:t}],o=await fetch("https://apps.abacus.ai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.ABACUSAI_API_KEY}`},body:JSON.stringify({model:"gpt-4.1-mini",messages:s,stream:!0,max_tokens:3e3,temperature:.7})});if(!o.ok)throw Error("Failed to get AI response");let u=new ReadableStream({async start(e){let r=o.body?.getReader(),t=new TextDecoder,a=new TextEncoder;try{for(;;){let{done:n,value:s}=await r?.read()||{done:!0,value:void 0};if(n)break;let o=t.decode(s);e.enqueue(a.encode(o))}}catch(r){console.error("Stream error:",r),e.error(r)}finally{e.close()}}});return new Response(u,{headers:{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-cache",Connection:"keep-alive"}})}catch(e){return console.error("AI Assistant error:",e),i.NextResponse.json({error:"Internal server error"},{status:500})}}let c=new n.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/ai-assistant/route",pathname:"/api/ai-assistant",filename:"route",bundlePath:"app/api/ai-assistant/route"},resolvedPagePath:"/home/ubuntu/wedding_planner_platform/app/app/api/ai-assistant/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:m,staticGenerationAsyncStorage:g,serverHooks:w}=c,h="/api/ai-assistant/route";function x(){return(0,o.patchFetch)({serverHooks:w,staticGenerationAsyncStorage:g})}},11826:(e,r,t)=>{t.d(r,{L:()=>d});var a=t(66291),n=t(64617),s=t(83178),o=t(3390),i=t.n(o);let d={adapter:(0,n.N)(s._),providers:[(0,a.Z)({name:"credentials",credentials:{email:{label:"Email",type:"email"},password:{label:"Password",type:"password"}},async authorize(e){if(!e?.email||!e?.password)return null;let r=await s._.user.findUnique({where:{email:e.email}});return r&&r.password&&await i().compare(e.password,r.password)?{id:r.id,email:r.email,name:r.name,partnerOneName:r.partnerOneName,partnerTwoName:r.partnerTwoName}:null}})],session:{strategy:"jwt"},pages:{signIn:"/auth/signin"},callbacks:{jwt:async({token:e,user:r})=>(r&&(e.partnerOneName=r.partnerOneName,e.partnerTwoName=r.partnerTwoName),e),session:async({session:e,token:r})=>(e?.user&&r?.sub&&(e.user.id=r.sub,e.user.partnerOneName=r.partnerOneName,e.user.partnerTwoName=r.partnerTwoName),e)}}},83178:(e,r,t)=>{t.d(r,{_:()=>n});var a=t(53524);let n=globalThis.prisma??new a.PrismaClient}};var r=require("../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),a=r.X(0,[372,329,3,609],()=>t(48783));module.exports=a})();